services:
  - type: web
    name: ai-waste-classification-bot
    env: python
    plan: free
    pythonVersion: "3.10"  # <== 新增這一行
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: DATABASE_URL
        value: sqlite:////data/database.db
      - key: PUSH_MESSAGE_ENABLED
        value: "true"
      - key: FLASK_ENV
        value: "production"
    disks:
      - name: data # (假設您建立的 Disk 名稱為 data)
        mountPath: /data
        sizeGB: 1



